name: GitHub Readme Snake CI

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#cca835&color_dots=#161b22,#1e415e,#2b5b84,#3b78a3,#4b91f1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch GitHub Trophies
        run: |
          curl -o "./dist/github-trophies.svg" "https://github-profile-trophy.vercel.app/?username=${{ github.repository_owner }}&column=6&margin-w=8&margin-h=8&no-frame=true&&title=MultiLanguage,Commits,Repositories,Stars,Followers,Experience&theme=darkhub"

      - name: Fetch Top Languages
        run: |
          curl -o "./dist/top-languages.svg" "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_Owner }}&layout=compact&hide_border=true&card_width=700&langs_count=14&bg_color=050608&title_color=ffffff&text_color=ffffff"

      - name: Fetch Activity Graph
        run: |
          curl -o "./dist/activity-graph.svg" "https://github-readme-activity-graph.vercel.app/graph?username=${{ github.repository_owner }}&theme=react-dark&bg_color=050608&hide_border=true&area=true&point=ffffff&days=30&radius=8&custom_title=⚡%20Activity%20Graph&height=350"

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Updated stats and snake animation"

